### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by seralouk** [dkamm/coinmarketcap-scraper#3]
Hi

```
python scrape.py --outfile small.csv --start 2018-01-01 --end 2018-01-31 --symbols BTC ETH
```

throws

```
Traceback (most recent call last):
  File "scrape.py", line 130, in <module>
    main()
  File "scrape.py", line 103, in main
    all_df = parse_all_response(requests.get(all_url()))
  File "scrape.py", line 36, in parse_all_response
    for tr in table.tbody.find_all('tr'):
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by ramonmazinga** [comment]
Same problem, this seems no longer to be working
